-- Criando Banco de dados e usando
CREATE database oficina;
use oficina;


CREATE TABLE PESSOA(
	ID_PESSOA INT auto_increment primary KEY,
    NOME VARCHAR(45) NOT NULL,
    SOBRENOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45),
    DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    TELEFONE CHAR(11) NOT NULL
); 

CREATE TABLE CLIENTE_PF(
	ID_CLIENTE_PF INT primary KEY,
    CPF CHAR(11) NOT NULL,
    RG CHAR(11) NOT NULL,
    CONSTRAINT FK_PF_PESSOA foreign key (ID_CLIENTE_PF) references PESSOA (ID_PESSOA),
    CONSTRAINT uniqueCPF unique (CPF),
    CONSTRAINT uniqueRG unique (RG)
);

CREATE TABLE CLIENTE_PJ(
	ID_CLIENTE_PJ INT primary KEY,
    CNPJ CHAR(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    NOME_FANTASIA VARCHAR(45) NOT NULL,
    CONSTRAINT FK_PJ_PESSOA foreign key (ID_CLIENTE_PJ) references PESSOA (ID_PESSOA),
    CONSTRAINT uniqueCNPJ unique (CNPJ)
);

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT PRIMARY KEY,
    MATRICULA INT NOT NULL,
    CARGO VARCHAR(45) NOT NULL,
    ESPECIALIDADE VARCHAR(45) NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_PESSOA foreign key (ID_FUNCIONARIO) references PESSOA (ID_PESSOA),
    CONSTRAINT uniqueMATRICULA_FUNCIONARIO unique (MATRICULA)
);

CREATE TABLE VEICULO(
	ID_VEICULO INT PRIMARY KEY auto_increment,
    MARCA VARCHAR(45) NOT NULL,
    MODELO VARCHAR(45) NOT NULL,
    MOTOR VARCHAR(45) NOT NULL,
    PLACA CHAR(8) NOT NULL,
    ANO INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    CONSTRAINT uniquePLACA unique (PLACA),
    CONSTRAINT FK_VEICULO_PESSOA foreign key (ID_PESSOA) references PESSOA (ID_PESSOA)
);

CREATE TABLE ORDEM_SERVICO(
	ID_ORDEM_SERVICO INT primary KEY auto_increment,
    DESCRICAO_SERVICO VARCHAR(200) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_ENTREGA DATE,
    VALOR_SERVICO DOUBLE NOT NULL,
    STATUS ENUM('Em Serviço', 'Pronto', 'Orçamento')
);

CREATE TABLE MAO_OBRA(
	ID_MAO_OBRA INT auto_increment PRIMARY KEY,
    TIPO_SERVICO VARCHAR (45) NOT NULL,
    TEMPO_SERVCO VARCHAR (45) NOT NULL,
    VALOR_HORA double
);

CREATE TABLE PECAS(
	ID_PECAS INT auto_increment PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    CODIGO VARCHAR(45) NOT NULL,
    FABRICANTE VARCHAR(45) NOT NULL,
    MODELO VARCHAR(45),
    VALOR DOUBLE
);

CREATE TABLE ATENDE_VEICULO(
	ID_PESSOA INT ,
    ID_VEICULO INT ,
    AUTORIZA_SERVICO BOOLEAN,
    CONSTRAINT primary key(ID_PESSOA,ID_VEICULO),
    CONSTRAINT FK_ATENDE_ID_PESSOA foreign key (ID_PESSOA) references PESSOA (ID_PESSOA),
    CONSTRAINT FK_ATENDE_ID_VEICULO foreign key (ID_VEICULO) references VEICULO (ID_VEICULO)
);

CREATE TABLE GERA_ORDEM_SERVICO(
	ID_PESSOA INT ,
    ID_ORDEM_SERVICO INT ,
    CONSTRAINT primary key(ID_PESSOA,ID_ORDEM_SERVICO),
    CONSTRAINT FK_OS_ID_PESSOA foreign key (ID_PESSOA) references PESSOA (ID_PESSOA),
    CONSTRAINT FK_OS_ID_ORDEM_SERVICO foreign key (ID_ORDEM_SERVICO) references ORDEM_SERVICO (ID_ORDEM_SERVICO)
);

CREATE TABLE MO_TEM_OS(
	ID_MAO_OBRA INT ,
    ID_ORDEM_SERVICO INT ,
    CONSTRAINT primary key(ID_MAO_OBRA,ID_ORDEM_SERVICO),
    CONSTRAINT FK_MO_ID_MAO_OBRA foreign key (ID_MAO_OBRA) references MAO_OBRA (ID_MAO_OBRA),
    CONSTRAINT FK_MO_ID_ORDEM_SERVICO foreign key (ID_ORDEM_SERVICO) references ORDEM_SERVICO (ID_ORDEM_SERVICO)
);

CREATE TABLE PECAS_OS(
	ID_PECAS INT ,
    ID_ORDEM_SERVICO INT ,
    CONSTRAINT primary key(ID_PECAS,ID_ORDEM_SERVICO),
    CONSTRAINT FK_PECA_ID_PECA foreign key (ID_PECAS) references PECAS (ID_PECAS),
    CONSTRAINT FK_PECA_ID_ORDEM_SERVICO foreign key (ID_ORDEM_SERVICO) references ORDEM_SERVICO (ID_ORDEM_SERVICO)
);